[package]
name = "wg-handshake"
version = "0.1.0"
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
blake2 = "0.8.0"
hmac = "0.7.1"
chacha20-poly1305-aead = "0.1.2"
generic-array = "0.13"

[dependencies.x25519-dalek]
version = "^0.5"
