[package]
name = "wg-handshake"
version = "0.1.0"
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
hex = "0.3"
spin = "0.5.0"
rand = "0.6.5"
blake2 = "0.8.0"
hmac = "0.7.1"
rust-crypto = "^0.2"
generic-array = "0.12"

[dependencies.x25519-dalek]
version = "^0.5"
