[package]
name = "wireguard-rs"
version = "0.1.0"
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"
license = "MIT"

[dependencies]
hex = "0.3"
spin = "0.5.0"
rand = "0.6.5"
blake2 = "0.8"
hmac = "0.7.1"
generic-array = "0.12.3"
zerocopy = "0.2.7"
byteorder = "1.3.1"
digest = "0.8.0"
lazy_static = "^1.3"
tokio = "0.1.22"
futures = "0.1.28"
arraydeque = "0.4.5"
treebitmap = "^0.4"
crossbeam-deque = "0.7"
hjul = "0.1.2"
ring = "0.16.7"
chacha20poly1305 = "^0.1"
aead = "^0.1.1"
clear_on_drop = "0.2.3"
parking_lot = "^0.9"
futures-channel = "^0.2"

[dependencies.x25519-dalek]
version = "^0.5"

[dependencies.subtle]
version = "2.1"
features = ["nightly"]

[dev-dependencies]
proptest = "0.9.4"
pnet = "^0.22"
