[package]
name = "wg-handshake"
version = "0.1.0"
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"

[dependencies]
rand = "0.7.0"

[dependencies.x25519-dalek]
version = "^0.5"
